version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: mambaforge-latest
  jobs:
    pre_build:
      - jupyter-book config sphinx .
      - jupyter-book build --path-output $READTHEDOCS_OUTPUT/html .

conda:
  environment: environment.yml
